-- Cambios en el modelo

INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, USUARIO, FECHA_CREACION_CUENTA)
VALUES
(1, 1, 'juanjop', '1993-07-12'),
(2, 2, 'rodriguez_ana', '1998-03-18'),
(3, 3, 'carlos_sachez', '1991-09-30'),
(4, 4, 'ele_garcia', '1987-12-05'),
(5, 5, 'mar_lpz', '1992-04-30'),
(6, 6, 'luisma', '1993-07-12'),
(7, 7, 'gon_sarita', '1998-03-18'),
(8, 8, 'pedrito91', '1991-09-30'),
(9, 9, 'ele_garcia', '1987-12-05'),
(10, 10, 'm_fdez', '1994-01-25');

CREATE TABLE SUSCRIPCION (
    ID_SUSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_SUSCRIPCION VARCHAR(50) UNIQUE,
    PRECIO DECIMAL(10, 2),
    DURACION_MESES INT
);

CREATE TABLE PAGO (
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CUENTA INT,
    FECHA_PAGO DATE,
    MONTO DECIMAL(10, 2),
    METODO_PAGO VARCHAR(50),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);

CREATE TABLE CUENTA_SUSCRIPCION (
    ID_CUENTA INT,
    ID_SUSCRIPCION INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PRIMARY KEY (ID_CUENTA, ID_SUSCRIPCION),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA),
    FOREIGN KEY (ID_SUSCRIPCION) REFERENCES SUSCRIPCION(ID_SUSCRIPCION)
);

CREATE TABLE DESCUENTO (
    ID_DESCUENTO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_DESCUENTO VARCHAR(50) UNIQUE,
    PORCENTAJE_DESCUENTO DECIMAL(5, 2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE PAGO_DESCUENTO (
    ID_PAGO INT,
    ID_DESCUENTO INT,
    PRIMARY KEY (ID_PAGO, ID_DESCUENTO),
    FOREIGN KEY (ID_PAGO) REFERENCES PAGO(ID_PAGO),
    FOREIGN KEY (ID_DESCUENTO) REFERENCES DESCUENTO(ID_DESCUENTO)
);

INSERT INTO SUSCRIPCION (TIPO_SUSCRIPCION, PRECIO, DURACION_MESES)
VALUES
    ('MENSUAL', 9.99, 1),
    ('TRIMESTRAL', 19.99, 3);

INSERT INTO CUENTA_SUSCRIPCION (ID_CUENTA, ID_SUSCRIPCION, FECHA_INICIO, FECHA_FIN)
VALUES
    (1, 1, '2023-01-01', '2023-02-01'),
    (2, 2, '2023-01-02', '2023-04-02');
